yosys -import
read_slang \
-I rsd/Processor/Src/ \
rsd/Processor/Src/MicroArchConf.sv \
rsd/Processor/Src/BasicTypes.sv \
rsd/Processor/Src/Memory/MemoryMapTypes.sv \
rsd/Processor/Src/RenameLogic/ActiveListIndexTypes.sv \
rsd/Processor/Src/Cache/CacheSystemTypes.sv \
rsd/Processor/Src/Memory/MemoryTypes.sv \
rsd/Processor/Src/Decoder/OpFormat.sv \
rsd/Processor/Src/Decoder/MicroOp.sv \
rsd/Processor/Src/RegisterFile/BypassTypes.sv \
rsd/Processor/Src/FetchUnit/FetchUnitTypes.sv \
rsd/Processor/Src/FloatingPointUnit/FPUTypes.sv \
rsd/Processor/Src/LoadStoreUnit/LoadStoreUnitTypes.sv \
rsd/Processor/Src/RenameLogic/RenameLogicTypes.sv \
rsd/Processor/Src/Scheduler/SchedulerTypes.sv \
rsd/Processor/Src/Pipeline/PipelineTypes.sv \
rsd/Processor/Src/IO/IO_UnitTypes.sv \
rsd/Processor/Src/Privileged/CSR_UnitTypes.sv \
rsd/Processor/Src/Debug/DebugTypes.sv \
rsd/Processor/Src/Core.sv \
rsd/Processor/Src/Pipeline/FetchStage/NextPCStage.sv \
rsd/Processor/Src/Pipeline/FetchStage/NextPCStageIF.sv \
rsd/Processor/Src/Pipeline/FetchStage/FetchStage.sv \
rsd/Processor/Src/Pipeline/FetchStage/FetchStageIF.sv \
rsd/Processor/Src/Pipeline/FetchStage/PC.sv \
rsd/Processor/Src/Pipeline/PreDecodeStage.sv \
rsd/Processor/Src/Pipeline/PreDecodeStageIF.sv \
rsd/Processor/Src/Pipeline/DecodeStage.sv \
rsd/Processor/Src/Pipeline/DecodeStageIF.sv \
rsd/Processor/Src/Pipeline/RenameStage.sv \
rsd/Processor/Src/Pipeline/RenameStageIF.sv \
rsd/Processor/Src/Pipeline/DispatchStage.sv \
rsd/Processor/Src/Pipeline/DispatchStageIF.sv \
rsd/Processor/Src/Pipeline/ScheduleStage.sv \
rsd/Processor/Src/Pipeline/ScheduleStageIF.sv \
rsd/Processor/Src/Pipeline/IntegerBackEnd/IntegerIssueStage.sv \
rsd/Processor/Src/Pipeline/IntegerBackEnd/IntegerIssueStageIF.sv \
rsd/Processor/Src/Pipeline/IntegerBackEnd/IntegerRegisterReadStage.sv \
rsd/Processor/Src/Pipeline/IntegerBackEnd/IntegerRegisterReadStageIF.sv \
rsd/Processor/Src/Pipeline/IntegerBackEnd/IntegerExecutionStageIF.sv \
rsd/Processor/Src/Pipeline/IntegerBackEnd/IntegerExecutionStage.sv \
rsd/Processor/Src/Pipeline/IntegerBackEnd/IntegerRegisterWriteStageIF.sv \
rsd/Processor/Src/Pipeline/IntegerBackEnd/IntegerRegisterWriteStage.sv \
rsd/Processor/Src/Pipeline/ComplexIntegerBackEnd/ComplexIntegerIssueStage.sv \
rsd/Processor/Src/Pipeline/ComplexIntegerBackEnd/ComplexIntegerIssueStageIF.sv \
rsd/Processor/Src/Pipeline/ComplexIntegerBackEnd/ComplexIntegerRegisterReadStage.sv \
rsd/Processor/Src/Pipeline/ComplexIntegerBackEnd/ComplexIntegerRegisterReadStageIF.sv \
rsd/Processor/Src/Pipeline/ComplexIntegerBackEnd/ComplexIntegerExecutionStageIF.sv \
rsd/Processor/Src/Pipeline/ComplexIntegerBackEnd/ComplexIntegerExecutionStage.sv \
rsd/Processor/Src/Pipeline/ComplexIntegerBackEnd/ComplexIntegerRegisterWriteStage.sv \
rsd/Processor/Src/Pipeline/MemoryBackEnd/MemoryIssueStage.sv \
rsd/Processor/Src/Pipeline/MemoryBackEnd/MemoryIssueStageIF.sv \
rsd/Processor/Src/Pipeline/MemoryBackEnd/MemoryRegisterReadStage.sv \
rsd/Processor/Src/Pipeline/MemoryBackEnd/MemoryRegisterReadStageIF.sv \
rsd/Processor/Src/Pipeline/MemoryBackEnd/MemoryExecutionStageIF.sv \
rsd/Processor/Src/Pipeline/MemoryBackEnd/MemoryExecutionStage.sv \
rsd/Processor/Src/Pipeline/MemoryBackEnd/MemoryAccessStageIF.sv \
rsd/Processor/Src/Pipeline/MemoryBackEnd/MemoryAccessStage.sv \
rsd/Processor/Src/Pipeline/MemoryBackEnd/MemoryTagAccessStageIF.sv \
rsd/Processor/Src/Pipeline/MemoryBackEnd/MemoryTagAccessStage.sv \
rsd/Processor/Src/Pipeline/MemoryBackEnd/MemoryRegisterWriteStageIF.sv \
rsd/Processor/Src/Pipeline/MemoryBackEnd/MemoryRegisterWriteStage.sv \
rsd/Processor/Src/Pipeline/FPBackEnd/FPIssueStage.sv \
rsd/Processor/Src/Pipeline/FPBackEnd/FPIssueStageIF.sv \
rsd/Processor/Src/Pipeline/FPBackEnd/FPRegisterReadStage.sv \
rsd/Processor/Src/Pipeline/FPBackEnd/FPRegisterReadStageIF.sv \
rsd/Processor/Src/Pipeline/FPBackEnd/FPExecutionStageIF.sv \
rsd/Processor/Src/Pipeline/FPBackEnd/FPExecutionStage.sv \
rsd/Processor/Src/Pipeline/FPBackEnd/FPRegisterWriteStage.sv \
rsd/Processor/Src/Pipeline/CommitStageIF.sv \
rsd/Processor/Src/Pipeline/CommitStage.sv \
rsd/Processor/Src/RegisterFile/RegisterFile.sv \
rsd/Processor/Src/RegisterFile/RegisterFileIF.sv \
rsd/Processor/Src/RegisterFile/BypassController.sv \
rsd/Processor/Src/RegisterFile/BypassNetwork.sv \
rsd/Processor/Src/RegisterFile/BypassNetworkIF.sv \
rsd/Processor/Src/ExecUnit/BitCounter.sv \
rsd/Processor/Src/ExecUnit/IntALU.sv \
rsd/Processor/Src/ExecUnit/Shifter.sv \
rsd/Processor/Src/ExecUnit/MultiplierUnit.sv \
rsd/Processor/Src/ExecUnit/PipelinedRefDivider.sv \
rsd/Processor/Src/ExecUnit/DividerUnit.sv \
rsd/Processor/Src/MulDivUnit/MulDivUnitIF.sv \
rsd/Processor/Src/MulDivUnit/MulDivUnit.sv \
rsd/Processor/Src/LoadStoreUnit/LoadStoreUnit.sv \
rsd/Processor/Src/LoadStoreUnit/LoadStoreUnitIF.sv \
rsd/Processor/Src/LoadStoreUnit/LoadQueue.sv \
rsd/Processor/Src/LoadStoreUnit/StoreQueue.sv \
rsd/Processor/Src/LoadStoreUnit/StoreCommitter.sv \
rsd/Processor/Src/FloatingPointUnit/FP32PipelinedAdder.sv \
rsd/Processor/Src/FloatingPointUnit/FP32PipelinedMultiplier.sv \
rsd/Processor/Src/FloatingPointUnit/FP32PipelinedFMA.sv \
rsd/Processor/Src/FloatingPointUnit/FP32PipelinedOther.sv \
rsd/Processor/Src/FloatingPointUnit/FP32DivSqrter.sv \
rsd/Processor/Src/FloatingPointUnit/FPDivSqrtUnit.sv \
rsd/Processor/Src/FloatingPointUnit/FPDivSqrtUnitIF.sv \
rsd/Processor/Src/RenameLogic/RenameLogic.sv \
rsd/Processor/Src/RenameLogic/RenameLogicIF.sv \
rsd/Processor/Src/RenameLogic/ActiveListIF.sv \
rsd/Processor/Src/RenameLogic/ActiveList.sv \
rsd/Processor/Src/RenameLogic/RMT.sv \
rsd/Processor/Src/RenameLogic/RetirementRMT.sv \
rsd/Processor/Src/RenameLogic/RenameLogicCommitter.sv \
rsd/Processor/Src/Decoder/Decoder.sv \
rsd/Processor/Src/Decoder/DecodedBranchResolver.sv \
rsd/Processor/Src/FetchUnit/BTB.sv \
rsd/Processor/Src/FetchUnit/BranchPredictor.sv \
rsd/Processor/Src/FetchUnit/Gshare.sv \
rsd/Processor/Src/FetchUnit/Bimodal.sv \
rsd/Processor/Src/Scheduler/SchedulerIF.sv \
rsd/Processor/Src/Scheduler/IssueQueue.sv \
rsd/Processor/Src/Scheduler/ReplayQueue.sv \
rsd/Processor/Src/Scheduler/WakeupSelectIF.sv \
rsd/Processor/Src/Scheduler/DestinationRAM.sv \
rsd/Processor/Src/Scheduler/ReadyBitTable.sv \
rsd/Processor/Src/Scheduler/Scheduler.sv \
rsd/Processor/Src/Scheduler/SelectLogic.sv \
rsd/Processor/Src/Scheduler/SourceCAM.sv \
rsd/Processor/Src/Scheduler/WakeupLogic.sv \
rsd/Processor/Src/Scheduler/WakeupPipelineRegister.sv \
rsd/Processor/Src/Scheduler/ProducerMatrix.sv \
rsd/Processor/Src/Scheduler/MemoryDependencyPredictor.sv \
rsd/Processor/Src/Cache/CacheSystemIF.sv \
rsd/Processor/Src/Cache/DCache.sv \
rsd/Processor/Src/Cache/DCacheIF.sv \
rsd/Processor/Src/Cache/ICache.sv \
rsd/Processor/Src/Cache/MemoryAccessController.sv \
rsd/Processor/Src/Cache/CacheFlushManager.sv \
rsd/Processor/Src/Cache/CacheFlushManagerIF.sv \
rsd/Processor/Src/Memory/Memory.sv \
rsd/Processor/Src/Recovery/RecoveryManager.sv \
rsd/Processor/Src/Recovery/RecoveryManagerIF.sv \
rsd/Processor/Src/ControllerIF.sv \
rsd/Processor/Src/Controller.sv \
rsd/Processor/Src/ResetController.sv \
rsd/Processor/Src/Privileged/InterruptController.sv \
rsd/Processor/Src/Privileged/CSR_Unit.sv \
rsd/Processor/Src/Privileged/CSR_UnitIF.sv \
rsd/Processor/Src/IO/IO_Unit.sv \
rsd/Processor/Src/IO/IO_UnitIF.sv \
rsd/Processor/Src/Primitives/FlipFlop.sv \
rsd/Processor/Src/Primitives/FreeList.sv \
rsd/Processor/Src/Primitives/Queue.sv \
rsd/Processor/Src/Primitives/RAM.sv \
rsd/Processor/Src/Primitives/LRU_Counter.sv \
rsd/Processor/Src/Primitives/Picker.sv \
rsd/Processor/Src/Primitives/Multiplier.sv \
rsd/Processor/Src/Primitives/Divider.sv \
rsd/Processor/Src/Debug/Debug.sv \
rsd/Processor/Src/Debug/DebugIF.sv \
rsd/Processor/Src/Debug/PerformanceCounter.sv \
rsd/Processor/Src/Debug/PerformanceCounterIF.sv \
-D RSD_SYNTHESIS \
-D RSD_SYNTHESIS_DESIGN_COMPILER \
-D RSD_MARCH_FP_PIPE \
--keep-hierarchy \
--top Core
hierarchy
